arm_joint_1_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: arm_2_joint_1
  pid: {p: 1000.0, d: 1.0}
arm_joint_2_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: arm_2_joint_2
  pid: {p: 1000.0, d: 1.0}
arm_joint_3_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: arm_2_joint_3
  pid: {p: 1000.0, d: 1.0}
arm_joint_4_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: arm_2_joint_4
  pid: {p: 1000.0, d: 1.0}
arm_joint_5_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: arm_2_joint_5
  pid: {p: 1000.0, d: 1.0}
